services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 5

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/197659111769/MyQueue
      - S3_BUCKET=yeidi-objects
      - AWS_REGION=us-east-1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  worker:
    build: ./worker
    environment:
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/197659111769/MyQueue
      - S3_BUCKET=yeidi-objects
      - AWS_REGION=us-east-1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 3
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped